#!/usr/bin/python

import readline 
import code
import cPickle as pickle
import sys
import obj

if len(sys.argv) < 2:
		sys.stderr.write("Usage: %s <Pickle file> [--quiet]\n"%(sys.argv[0]))
		sys.exit(1)

pklJar = open(sys.argv[1],"rb")
datasets = pickle.load(pklJar) 
print 'data is stored in variable "datasets"'
vars = globals().copy()
vars.update(locals())
shell = code.InteractiveConsole(vars)
shell.interact()
